// event constants for emitting events between client and server
const COMMUNITY_CHAT = 'COMMUNITY_CHAT'
const USER_CONNECTED = 'USER_CONNECTED'
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
const MESSAGE_SENT = 'MESSAGE_SENT'
const USER_DISCONNECTED = 'USER_DISCONNECTED'
const TYPING = 'TYPING'
const VERIFY_USER = 'VERIFY_USER'
const LOGOUT = 'LOGOUT'

export {
    COMMUNITY_CHAT,
    USER_CONNECTED,
    MESSAGE_RECEIVED,
    MESSAGE_SENT,
    USER_DISCONNECTED,
    TYPING,
    VERIFY_USER,
    LOGOUT
}
